[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "your-pre-commit-hook"
version = "0.1.0"
authors = [{name = "Your Name", email = "email@example.com"},]
description = "TODO"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 1 - Planning",  # update later
    "Programming Language :: Python"
]
urls.Homepage = "https://example.com"
urls.Documentation = "https://example.com/docs"

dependencies = ["your-hook-dependencies"]
requires-python = ">=3.8"
optional-dependencies.dev = [
    "pre-commit",  # so you can run hooks on the codebase
    "pytest",  # remember to add tests for your hook
]

# TODO: update `your-script-name` and the path
scripts.your-script-name = "your_pkg.your_module:hook_function"

# optional (if you are making a package)
[tool.setuptools.packages.find]
where = ["src"]
