[project]
name = "pre-commit-workshop"
version = "0.1.0"
authors = [{name = "Your Name", email = "email@example.com"},]
description = "A pre-commit hook created during the workshop."
readme = "README.md"

requires-python = ">=3.10"
dependencies = []  # TODO: declare any dependencies

# TODO: update `your-script-name` with the name of your choice
# TODO: update `pkg.module:function` to point to your function
scripts.your-script-name = "pkg.module:function"

[dependency-groups]
dev = [
  "pre-commit",  # so you can run hooks
